FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY run_federated_rounds.py .

RUN pip install requests && \
    apt-get update && \
    apt-get install -y curl && \
    curl -O https://dl.min.io/client/mc/release/linux-amd64/mc && \
    chmod +x mc && mv mc /usr/local/bin/

CMD ["python", "run_federated_rounds.py"]
