name: fedvtp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - tqdm
  - scikit-learn
  - ipython
  - jupyter
  - pip:
      - torch==2.0.1
      - torchvision==0.15.2
      - torchaudio==2.0.2
      - numexpr
      - einops
      - loguru
      - opacus