#minio-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
spec:
  selector:
    app: minio  # this label MUST match what's on your MinIO pod/deployment
  ports:
    - name: http
      port: 9000
      targetPort: 9000
